addReviewers: true
addAssignees: author
numberOfReviewers: 1
useReviewGroups: true


reviewGroups:
  sss4920:
    - Junyeong-An
  kduoh99:
    - Rommmu
  Junyeong-An:
    - giwoong01

useAssigneeGroups: false
