addReviewers: true
addAssignees: author
numberOfReviewers: 1
useReviewGroups: true
useAssigneeGroups: false

reviewerGroups:
  sss4920:
    - Junyeong-An
  kduoh99:
    - Rommmu
  Junyeong-An:
    - giwoong01
